config/routes.rb
Rails.application.routes.draw do

  mount Adeia::Engine => "/admin"

  root to: redirect('https://rencontredejeunesse.ch')

  resources :sessions, only: :create
  delete "signout", to: "sessions#destroy"
  get "signin", to: "sessions#new"

  scope "order_bundles/:key" do
    resources :option_orders, only: [:new, :create]
  end

  scope ":key" do
    resources :forms, only: [:new, :create]
  end

  #
  # Users
  #

  resources :users, only: [:new, :create], path: "signup" do
    get "success", on: :collection
  end

  namespace :users do

    resources :verification, only: [:new, :edit]
    resources :password_resets, only: [:new, :create, :edit, :update]

  end

  #
  # Connect
  #

  namespace :connect do

    root to: "users#show"
    get "edit", to: "users#edit"
    patch "update", to: "users#update"

    resources :refunds, only: :create

    resources :orders, only: [:index, :show, :invoice, :ticket] do
      get "pending", on: :collection
      member do
        get 'invoice'
        get 'ticket'
      end
    end
    resources :option_orders, only: [:index, :show, :destroy]

  end

  #
  # ORDERS
  #

  resources :orders, only: :destroy do
    # complete the order and proceed to payment
    post "pay", on: :member

    %w(success failed).each do |status|
      get "#{status}", on: :collection
    end
  end
    
  namespace :orders do

    # postfinance
    post "state_update", to: "webhooks#state_update"
    post "refund_update", to: "webhooks#refund_update"

    # complete free or invoice order
    resources :completion, only: :update, controller: :completion

    resources :payments, only: [:show] do
      post "pay", on: :member
    end

    # user update from order
    scope ":id/user", constraints: { id: /\d*/ }, as: :user do
      get "edit", to: "users#edit"
      patch "update", to: "users#update"
    end

    scope "(:key)" do

      # order a ticket for an event
      resources :events, only: [:new, :create, :edit, :update] do
        get "confirmation", on: :member
      end

      # Order from a bundle
      resources :bundles, only: [:new, :edit, :update] do
        get "confirmation", on: :member
      end

      # sign in/up before order
      resources :users, only: [:new, :create]

    end

  end

  #
  # ADMIN
  #

  namespace :admin do

    root to: "base#index"

    resources :volunteers, only: [:index, :show]
    resources :badges, only: [:index, :create, :dev] do
      get "volunteer", on: :collection
      get "prayer", on: :collection
      get "dev", on: :collection
    end
    resources :option_orders
    resources :items

    resources :users, except: :show
    resources :discounts, except: [:edit, :update]
    resources :payments, except: [:index, :new]
    resources :testimonies, except: [:show, :new, :create]
    resources :posts
    resources :comments, only: [:edit, :update, :destroy]

    namespace :orders do

      scope "(/:bundle_key)" do
        resources :events  

        resources :registrants, only: [:index, :show, :update] do
          get "export", on: :collection
        end

        resources :checkin, only: [:index, :create, :update]
      end

    end

    namespace :forms do

      resources :completed_forms, only: [:index, :show, :destroy]

    end

    scope "/rj24" do
      get "stats", to: "rj24#stats"
    end

  end

end

app/views/layouts/headers/_admin.html.erb
<header>
  <%= link_to image_tag("layout/logo.png", class: "logo"), connect_root_path %>

  <div class="user">
    <div><%= current_user.try(:full_name) || "Invité" %></div>
    <div class="edit">
      <%= link_to connect_edit_path do %>
        <%= image_tag("icons/gear.png") %>
        <span>Mon compte</span>
      <% end %>
    </div>
  </div>
  <div class="signout"><%= link_to "Déconnexion", signout_path, method: :delete %></div>

  <ul>
    <li class="text">Admininistration</li>
    <% if can?(:read, "admin/users") %><li><%= link_to "Utilisateurs", admin_users_path %></li><% end %>
    <li class="text">Commandes</li>
    <% if can?(:read, "admin/orders/checkin") %><li><%= link_to "Checkin", admin_orders_checkin_index_path %></li><% end %>
    <% if can?(:read, "admin/orders/events") %><li><%= link_to "Commandes", admin_orders_events_path %></li><% end %>
    <% if can?(:read, "admin/orders/registrants") %><li><%= link_to "Participants", admin_orders_registrants_path %></li><% end %>
    <% if can?(:read, "admin/discounts") %><li><%= link_to "Codes promotionels", admin_discounts_path %></li><% end %>
    <% if can?(:read, "admin/items") %><li><%= link_to "Produits", admin_items_path %></li><% end %>
    <li class="text">Commandes spéciales</li>
    <% if can?(:read, "admin/option_orders") %><li><%= link_to "Commandes spéciales", admin_option_orders_path %></li><% end %>
    <li class="text">Bénévoles</li>
    <% if can?(:read, "admin/volunteers") %><li><%= link_to "Bénévoles", admin_volunteers_path %></li><% end %>
    <% if can?(:read, "admin/volunteers") %><li><%= link_to "Badges", admin_badges_path %></li><% end %>
  </ul>
</header>